### ISSUE TITLE
Camera Part

### ISSUE THREAD

**Issue by keepitsane** [tigrisli/nouns-polaroid#1]
Hello I was curious which camera you are using for this. Is it Raspberry Pi High Quality Camera with a bigger lens?

Thanks in advance and cool build, would definitely love more instructions on parts if you have it 😎

**Comment by tigrisli** [comment]
Hi, I'm using the Raspberry Pi High Quality Camera with the 6mm wide angle lens. And thank you! I'll be adding instructions over the next few weeks with images and all that so you'll be able to re-build this project yourself + a 3D printable enclosure for it! ☺️
